### ISSUE TITLE
Temporary patch doesn't seem to work

### ISSUE THREAD

**Issue by solitonmedic** [initPRAGMA/kit-kat#8]
NTRViewer cant really seem to stream video from certain games (i.e. Persona Q, Luigi's Mansion: Dark Moon, or Fire Emblem: Awakening). 

kit-kat attempts to connect through patching, and stays that way, forcing me to close it and launch it again to open NTRViewer without the patch. These games can't be streamed without the patch however. Patching with NTRViewer on doesn't seem to do much either.

**Comment by initPRAGMA** [comment]
These games work fine for me? Can you try again?

**Comment by chickenmatt5** [comment]
I have the same issue with sending the temporary patch. kit-kat just stays on "Trying to connect..."

**Comment by initPRAGMA** [comment]
This was fixed ages ago, not sure why this issue is still open

**Comment by allstevenu** [comment]
What you need to do is get out of the game(to your homescreen ) and try it again. This happens because you can't connect because you have no internet connection. When you go to the homescreen you are allowing a short burst of Internet. If you can't get the timeing right try reopening the game but before you open it try sending q pack with no app open
